### ISSUE TITLE
 The 'wrapper.port' system property was not set.

### ISSUE THREAD

**Issue by logongas** [worldline/openshift-sonarqube#4]
In sonar v4.5.4

I got the error:

--> Wrapper Started as Daemon
Java Service Wrapper Community Edition 64-bit 3.5.9
  Copyright (C) 1999-2011 Tanuki Software, Ltd. All Rights Reserved.
    http://wrapper.tanukisoftware.com

Launching a JVM...
Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
  Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.

JVM exited while loading the application.
The 'wrapper.port' system property was not set.
Exception in thread "main" java.lang.ExceptionInInitializerError: The 'wrapper.port' system property was not set.
        at org.tanukisoftware.wrapper.WrapperManager.privilegedClassInit(WrapperManager.java:528)
        at org.tanukisoftware.wrapper.WrapperManager.access$000(WrapperManager.java:103)
        at org.tanukisoftware.wrapper.WrapperManager$1.run(WrapperManager.java:328)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.tanukisoftware.wrapper.WrapperManager.<clinit>(WrapperManager.java:325)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:190)
        at org.tanukisoftware.wrapper.WrapperSimpleApp.class$(WrapperSimpleApp.java:86)
        at org.tanukisoftware.wrapper.WrapperSimpleApp.<init>(WrapperSimpleApp.java:133)
        at org.tanukisoftware.wrapper.WrapperSimpleApp.main(WrapperSimpleApp.java:485)
Exception in thread "Wrapper-Shutdown-Hook" java.lang.NoClassDefFoundError: Could not initialize class org.tanukisoftware.wrapper.WrapperManager
        at org.tanukisoftware.wrapper.WrapperManager$2.run(WrapperManager.java:456)
Automatic JVM Restarts disabled.  Shutting down.
<-- Wrapper Stopped
--> Wrapper Started as Daemon
Java Service Wrapper Community Edition 64-bit 3.5.9
  Copyright (C) 1999-2011 Tanuki Software, Ltd. All Rights Reserved.
    http://wrapper.tanukisoftware.com

Launching a JVM...
JVM exited while loading the application.
Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
  Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.

The 'wrapper.port' system property was not set.
Exception in thread "main" java.lang.ExceptionInInitializerError: The 'wrapper.port' system property was not set.
        at org.tanukisoftware.wrapper.WrapperManager.privilegedClassInit(WrapperManager.java:528)
        at org.tanukisoftware.wrapper.WrapperManager.access$000(WrapperManager.java:103)
        at org.tanukisoftware.wrapper.WrapperManager$1.run(WrapperManager.java:328)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.tanukisoftware.wrapper.WrapperManager.<clinit>(WrapperManager.java:325)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:190)
        at org.tanukisoftware.wrapper.WrapperSimpleApp.class$(WrapperSimpleApp.java:86)
        at org.tanukisoftware.wrapper.WrapperSimpleApp.<init>(WrapperSimpleApp.java:133)
        at org.tanukisoftware.wrapper.WrapperSimpleApp.main(WrapperSimpleApp.java:485)
Exception in thread "Wrapper-Shutdown-Hook" java.lang.NoClassDefFoundError: Could not initialize class org.tanukisoftware.wrapper.WrapperManager
        at org.tanukisoftware.wrapper.WrapperManager$2.run(WrapperManager.java:456)
Automatic JVM Restarts disabled.  Shutting down.
<-- Wrapper Stopped

**Comment by jewzaam** [comment]
I hit this as well trying to go to sonarqube 5.1.2.
Reverting back to 4.3.2 which works.
